### ISSUE TITLE
Please remove SlashcoLogo.vtf/vmt and sc_lobby.vmf

### ISSUE THREAD

**Issue by VCSoldier** [Mantibro/SlashCo#8]
This is my texture, and also remove the map from the files too since i noticed they are both 20 days old (meaning its still my map :) )

if you close this without action i will assume you like breaking copyright laws (all material made by a person is copyrighted automatically, what copyright level it is at is their discretion) so i would probably remove it even if you have a new map, i have no business sharing my work with someone who was desecrating a grave on someones build while wearing a nazi armband on their pac3 model,

**Comment by textstack** [comment]
Let me explain this situation: after seeing a clip of Manti jokingly saying he'd "stuff [a bee] all up with estrogen and cut that dick off", VC spontaneously decided to leave and disassociate with the entire project. From reading his messages, his thought process seemed to be that, without being given any context to the clip, he initially thought the clip was directed at a particular bee pac that a player from a different community had (In reality, Manti was reacting to porn that was sent to him). VC went on to associate the clip with an incident of actual, targeted harassment of a minor--in which a completely different person described in detail how they would violate an underage child while directly in front of them. I believe the association mainly comes from Manti saying "cut that dick off" and said person's detailed description of a similar act.

From my experience, VC suddenly making explosive exits like this isn't new. I'm aware of at least four times prior in which VC has 'left' a community, one of which wasn't even 2 weeks prior to him leaving here. What's particularly odd is that VC has made jokes in a similar, if not more extreme, caliber than in the clip of Manti, describing sexual situations to a level of detail I simply cannot quote here. Perhaps VC really is _genuinely_ concerned over Manti's character as the lead developer, but I think the wording of this very issue speaks for itself. I'll leave a copy of it below.

> This is my texture, and also remove the map from the files too since i noticed they are both 20 days old (meaning its still my map :) )

> if you close this without action i will assume you like breaking copyright laws (all material made by a person is copyrighted automatically, what copyright level it is at is their discretion) so i would probably remove it even if you have a new map, i have no business sharing my work with someone who was desecrating a grave on someones build while wearing a nazi armband on their pac3 model,

Also, regarding that last sentence: VC is referring to Kristin_13_1994, _not_ Manti. Kristin actually did do this, around a year and a half ago. We're accepting his work because he simply decided to contribute. This is an open source project.

**Comment by VCSoldier** [comment]
Oh also he could've apologized, something pretty easy to do, but his ego had to keep him afloat where he then acted like saying that even drunk is ok to say as a gamemode developer, Its obvious he has no actual thought to what he says, and if he's saying this kind of thing while drunk, then maybe he shouldn't drink. Just something I had a thought about

**Comment by VCSoldier** [comment]
Goto forum.ijwtb.net. click the sandbox drop down. Click the bans. In there tick player name and then search navu, this is kofuku, you really think I should sit idly by accepting someone like this sitting in a gamemode server where their is definitely children actively discussing in jt

**Comment by VCSoldier** [comment]
But suuure Ive left in explosive unexpected ways!!! Definitely not very obvious reasons that are reasonable in everyway

**Comment by VCSoldier** [comment]
I can explain the other shit. This server is so toxic where I basically just became like everyone else. Overly disgusting and toxic. Because it's the only way I could actually avoid the majority of the bother I would usually get, I don't know if you know this. But trying to fit in such a toxic place requires someone to become equally if not worse in toxicity

**Comment by VCSoldier** [comment]
Do I regret saying it? Yes. Definitely, I feel like I have definitely gone too far some times, this is something I bet none of the people who have harrassed me have thought, because they don't care what they say, they simply have become so lacking of emotions they can say literally anything

**Comment by VCSoldier** [comment]
Now youve probably realized this has kinda backfired on you, you should've just done what I asked

**Comment by Papyrus61** [comment]
https://user-images.githubusercontent.com/20608812/186269935-877c2ad1-b064-4139-8113-cd9d91996fe3.mp4

**Comment by JimAlwaysWins** [comment]
Vee: if only there was a proper way to describe people...

The hard R:

**Comment by Papyrus61** [comment]
https://user-images.githubusercontent.com/20608812/186271701-8e412a0e-d97a-4515-bd78-277d614dbd00.mp4

**Comment by VCSoldier** [comment]
5hats cute. Now show jimalwayswins saying the same thing, or dynamx entire message history being the same thing, your nitpicking me for trying to fit in with two people who are ironically racist and seem to think that it means I'm actually racist, the amount of dicksucking here is crazy bro if you want to act so immature lol

**Comment by VCSoldier** [comment]
Erm vee is racist vee is racist!!! Why didn't you ban me? Kick me? Warn me? this is entirely your issue to be dealing with if it truly was an issue to you, that's because your using this in a straw man way, to try make it seem like I'm the worse one, I'm sorry you need to stoop to such lows to try make it seem like I'm the bad guy, when it's you whos really losing, since I have never been kicked for any of these comments, only time I was ever kicked was when me and @Mantibro were annoying kofuku early on in the servers age by constantly pinging him

**Comment by VCSoldier** [comment]
You can seriously keep trying though, it's funny watching you ruin your own reputation when this entire thing could've been avoided 2 days ago if your main developer simply apologised for what he did, something so easy that it's laughable to think he seriously went out of his way to not apologise

**Comment by VCSoldier** [comment]
And you seem to post this as if I act like this everywhere, odd how it's literally just in your server where two of the most toxic people basically use the nword as much as fuck in their sentences, one of which who has more power in the server than me, and can basically control my name and roles as he pleases,

**Comment by VCSoldier** [comment]
I'd love to keep this going but honestly talking here is hilariously sad seeing how far your going just to try explain how me leaving is bad and that I'm a dumbass

**Comment by JimAlwaysWins** [comment]
ok

**Comment by Papyrus61** [comment]
k

**Comment by JimAlwaysWins** [comment]
> 

699 times says otherwise

**Comment by VCSoldier** [comment]
Jimalwayswins I'd include the fact your a moderator on the server and even outside of the server you have probably said it more than I have ever, 699 times for "nigga" specifically is literally nothing, as I am rarely using it in the way it was originally intended for, and the times I AM using it that way, it is in the same ironic fashion that you , specifically YOU use it that way, I don't actually hate black people. There is no posts on any social medias or anything other than this specific server where I have said this stuff, because Im not actually racist, now true you could say that saying it in general is bad, but that doesn't excise the fact I was basically only doing it to avoid being harassed by you @JimAlwaysWins , I like to remind you that you were named @hard-r where a majority of those hard rs come from, where you then changed it back to Jim,  you are literally making the example of a straw man arguement. But ok let's say I'm in the wrong, I'm still not allowing a dude who got a kid to piss on camera for his disgusting fetish to sit in any server I own, since that's why kofuku was banned from ijwtb, I don't care how much he's "changed" either, so that's already even a pretty bad look on you even if I'm wrong

Or the fact that in multiple occasions I have heard rumors about the owner of the server creating a nsfw model of a minors Sona, (not gonna disclose name, but he probably knows what I'm on about)
Or the fact that in the least ironic tone, with KitKat to back him up, he approached me on ijwtb in Gmod asking if he could make a nsfw version of my vee model, which even as a joke. Is a fuckint moronic thing to ask a minor,

**Comment by VCSoldier** [comment]
So sure if I'm wrong for the nword that's... 1 for you... And still a majority for me,

**Comment by VCSoldier** [comment]
Oh here's something I could do, I could post the evidence that got kofuku banned from ijwtb in here, maybe thatll have some backing to what I say,

Funny to think that if manti didn't act like such an egotistical brat, where apologising in the discord would've been easier to do, that he would've just avoided this shit, because your really pushing yourselfs with the attempt to ruin my image

**Comment by JimAlwaysWins** [comment]
> 

the fact you talked alot of shit about a person leaving because you were infact bullying them speaks volume
![nice 1](https://user-images.githubusercontent.com/111923963/186277547-6321124f-ca33-4889-9b0b-6b79fcc768cb.PNG)

**Comment by JimAlwaysWins** [comment]
> JimAlwaysWins

and then proceeded to act all nice in their dms and act like a friend afterwards is wild

**Comment by VCSoldier** [comment]
![IMG_8827](https://user-images.githubusercontent.com/50423227/186278006-129a74f8-679a-4095-8cdf-57b8cb750bdc.jpg)
![unknown-125](https://user-images.githubusercontent.com/50423227/186278013-4957a441-c0bb-4fc6-9e53-5139e62aabe4.jpg)

You really wanted to go this route. Dawg I mean. Honestly, your stubborness became your downfall,

To anyone not in the veteran team. This is navu. Kofuku. the guy with the dancing rat avatar,

**Comment by VCSoldier** [comment]
Now why you would want to act like fucking morons in the situation knowing that I was speaking the truth, is honestly kinda fucking bewildering, you literally just led yourself into a deeper hole by escalating it with hypocrisy

**Comment by VCSoldier** [comment]
15 hours wasted, your reputation definitely ruined by now. And all because you couldn't say sorry. Really? You went this far. This far with this shit. That you would rather it be your downfall, the gamemodes downfall, something I wouldnt have originally wanted to be jones

**Comment by totallynotundo** [comment]
that fact that you are continuing to argue with us despite all of your files being removed speaks fucking volumes on how insistent you are on trying to bring us down, grow the fuck up dude.

**Comment by JimAlwaysWins** [comment]
> 15 hours wasted, your reputation definitely ruined by now. And all because you couldn't say sorry. Really? You went this far. This far with this shit. That you would rather it be your downfall, the gamemodes downfall, something I wouldnt have originally wanted to be jones

in all of your tyrants about someone being drunk during gartic phone, you never once asked for a sorry lmao

**Comment by VCSoldier** [comment]
> > 15 hours wasted, your reputation definitely ruined by now. And all because you couldn't say sorry. Really? You went this far. This far with this shit. That you would rather it be your downfall, the gamemodes downfall, something I wouldnt have originally wanted to be jones
> 
> in all of your tyrades about someone being drunk during gartic phone, you never once asked for a sorry lmao, claiming you asked him to apologise is the most cap i ever heard!!!

So I'm expected to ask for an apology for something that should warrant an apology to literally anyone who saw it out of context, mind you this entire thing could've stopped at my second comment. Noone would've seen this, because barely anyone looks at closed issues.
But now those that do are going to see the hilariously bsd attempt you morons took to try somehow better yourselfs, using handpicked images, while the own evidence video is hypocritical, as the images at the start are leaked, edited to harass me specifically, proving my point you would do literally anything to get under my skin. bravo idiots, you have done the most moronic action I have ever seen in my entire time of playing gmod,

**Comment by JimAlwaysWins** [comment]
> 15 hours wasted, your reputation definitely ruined by now. And all because you couldn't say sorry. Really? You went this far. This far with this shit. That you would rather it be your downfall, the gamemodes downfall, something I wouldnt have originally wanted to be honest, and all because your ego is so inflated, you think nitpicking my specific comments means I'm wrong, Jim. You literally complained about undo the minute he left, even before that. I genuinely did feel bad. I genuinely did want to befriend him, I wanted to apologize, I'm sorry It may have seemed like I didn't, but I did. You had to just keep berating me in the most moronic fashion, knowing everything your using against me is the half truth, hiding context and other points

you really like moronic, whats moronic is the fact everything you've worked on was already removed and replaced (by even better shit lmoa) and your still continuing to attempt to get us "cancelled"""" i think this is just soy boy copium because child got removed from funny group project

**Comment by JimAlwaysWins** [comment]
> > > 15 hours wasted, your reputation definitely ruined by now. And all because you couldn't say sorry. Really? You went this far. This far with this shit. That you would rather it be your downfall, the gamemodes downfall, something I wouldnt have originally wanted to be jones
> > 
> > 
> > in all of your tyrades about someone being drunk during gartic phone, you never once asked for a sorry lmao, claiming you asked him to apologise is the most cap i ever heard!!!
> 
> So I'm expected to ask for an apology for something that should warrant an apology to literally anyone who saw it out of context, mind you this entire thing could've stopped at my second comment. Noone would've seen this, because barely anyone looks at closed issues. But now those that do are going to see the hilariously bsd attempt you morons took to try somehow better yourselfs, using handpicked images, while the own evidence video is hypocritical, as the images at the start are leaked, edited to harass me specifically, proving my point you would do literally anything to get under my skin. bravo idiots, you have done the most moronic action I have ever seen in my entire time of playing gmod,

699 times of saying the n word HAS to be cherry picking............

**Comment by VCSoldier** [comment]
Lol well, good luck to you on this, pretty sure you can just delete issues meaning you could've just marked as completed and deleted it,knowing I wasted your time on this shit is hilarious to me. I have literally nothing to do for a few days anyway so this was fun to me to see how i really should've avoided the server when you reinv kofu

**Comment by JimAlwaysWins** [comment]
> Lol well, good luck to you on this, pretty sure you can just delete issues meaning you could've just marked as completed and deleted it,knowing I wasted your time on this shit is hilarious to me. I have literally nothing to do for a few days anyway so this was fun to me to see how i really should've avoided the server when you reinv kofu

bro  typed paragraphs and said HAH I WASTED YOUR TIME.... naww

**Comment by VCSoldier** [comment]
I did say I have literally NOTHING to do for a few days, and what I have done has literally 0 impact on how long it takes me to write this shit up

**Comment by totallynotundo** [comment]
you were wasting your own time with this, your association with with this gamemode is already wiped, all gone. i dont have a fucking single clue as to why you continue with this bullshit to "cancel us".

**Comment by JimAlwaysWins** [comment]
> I did say I have literally NOTHING to do for a few days, and what I have done has literally 0 impact on how long it takes me to write this shit up

that is crazy bro

**Comment by VCSoldier** [comment]
Honestly should've just deleted 5ge issue, I looked it up, it was possible and I would've stopped, and Im being serious, you could've deleted the issue and I literally would've stopped because it would confirm you have done the task, as I would've have looked at the branches which would've shown me that yes you did do this

**Comment by VCSoldier** [comment]
There was literally 0 reason to reply to this issue, you did it out of pure moronic malice towards me, and considering its issue 8 and I don't see any other issues, pretty much proves my point on the fact you did this for your own reasons

**Comment by totallynotundo** [comment]
i know for a damn fact that you wouldnt have stopped because your insistent ass is gonna continue trying to argue with us

**Comment by JimAlwaysWins** [comment]
> There was literally 0 reason to reply to this issue, you did it out of pure moronic malice towards me, and considering its issue 8 and I don't see any other issues, pretty much proves my point on the fact you did this for your own reasons

that is crazy aswell bro

**Comment by VCSoldier** [comment]
You should probably just delete this issue, I'm tired anyway think I need a snooze from actual shit I done irl

**Comment by JimAlwaysWins** [comment]
> You should probably just delete this issue, I'm tired anyway think I need a snooze from actual shit I done irl

i work a 7 hour shift at school....... i live that irl shit fr fr

**Comment by totallynotundo** [comment]
brooo... i got that epileptic whore house security guard job dawg.....

**Comment by VCSoldier** [comment]
Lol I'm not even in any sort of education right now, my college course starts in like a week from now, I've been busy helping redo my house, it must be hard to imagine a world outside the pc screen for you guys. And honestly that sucks. Hope u recover 🙏

**Comment by totallynotundo** [comment]
says the fucker blasting his keyboard at like 5000 words per minute trying to win over an argument that you'll lose anyway 💀

**Comment by JimAlwaysWins** [comment]
> Lol I'm not even in any sort of education right now, my college course starts in like a week from now, I've been busy helping redo my house, it must be hard to imagine a world outside the pc screen for you guys. And honestly that sucks. Hope u recover 🙏

fatherless and not in school......... type out 83688 wpm essay to combat argument......... -sun tzu

**Comment by VCSoldier** [comment]
Idk... Having a pedophile in your staff ranks is pretty unbeatable in the terms of who's losing here, sucks for you guys that you completely ignored it because you believe his word of him saying he changed

**Comment by totallynotundo** [comment]
i can tell you are running out of arguments, pulling out pre existing points that literally serve no purpose, jesus man grow the fuck up.

**Comment by JimAlwaysWins** [comment]
> Idk... Having a pedophile in your staff ranks is pretty unbeatable in the terms of who's losing here, sucks for you guys that you completely ignored it because you believe his word of him saying he changed

please answer my phone call

**Comment by VCSoldier** [comment]
I have no new points to add, I have discussed everything that defends me, I told you to delete the issue like 3 comments ago but your just continuing it, idc lol this is just fun seeing how long you will go after I literally suggested a way to shut me up

**Comment by JimAlwaysWins** [comment]
> I have no new points to add, I have discussed everything that defends me, I told you to delete the issue like 3 comments ago but your just continuing it, idc lol this is just fun seeing how long you will go after I literally suggested a way to shut me up

that is crazy lil bro

**Comment by totallynotundo** [comment]
idk its just fun to bully you

> I have no new points to add, I have discussed everything that defends me, I told you to delete the issue like 3 comments ago but your just continuing it, idc lol this is just fun seeing how long you will go after I literally suggested a way to shut me up

**Comment by VCSoldier** [comment]
Lol proving my point that you are just doing this for ego reasons, enjoy that then I don't care, atleast we can agree yuno miles is fire though

**Comment by JimAlwaysWins** [comment]
> Author

i dont care answer my hotline bling

**Comment by totallynotundo** [comment]
yeah bro

**Comment by VCSoldier** [comment]
💯 💯 🙏 this shit fire or what. Mad dog hittin bars 🙏 💯 💯

**Comment by VCSoldier** [comment]
If you a real one!! Hit me up with yo number below \/ only real ones get accepted into the gang

**Comment by totallynotundo** [comment]
you are trying to befriend us to get back in and its not gonna happen

**Comment by JimAlwaysWins** [comment]
> If you a real one!! Hit me up with yo number below / only real ones get accepted into the gang

my nuts feel hairy

**Comment by totallynotundo** [comment]
mine too bro

**Comment by VCSoldier** [comment]
I'm not trying to befriend you lol, I don't give a fuck, im literally just seeing how long you guys are gonna keep this issue a thing instead of deleting it, 

Shit is wacky bro go crazy dawg it's nuts how wacky this is

**Comment by JimAlwaysWins** [comment]
> 

shut up you sound like a raging child

**Comment by VCSoldier** [comment]
If anything looking at you specifically undo shows me what I was before I finally broke the cycle and told you all to delete my shit, well anyway I gotta paint shit tommorow ttyl :)

**Comment by JimAlwaysWins** [comment]
> If anything looking at you specifically undo shows me what I was before I finally broke the cycle and told you all to delete my shit, well anyway I gotta paint shit tommorow ttyl :)

paint a picture with your dad then

**Comment by totallynotundo** [comment]
my nuts itch
